## **EXP 4 :- Data Preprocessing-Normalizing, scaling, balancing data set**

**What is NORMALISING?**
Normalizing is the process that aligns data values to a common scale. This makes machine learning easier and finding the relationship between data easier and more efficient.
**Normalization Techniques:-**
1] Min-Max Scaling
2]Z Score Normalisation
3]Decimal Normalisation
4]Log Scaling
5]Robust Scaling

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dframe=pd.read_csv("/content/drive/MyDrive/Social_Network_Ads (1).csv")
dframe

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [4]:
#to handle string values and categorical data we use encoding
#-one hot-encoding----converts values into binary data and creates dummy columns
#label-encoding----- gives values 1,2,3,4... according to alphabetical order

In [5]:
from sklearn.preprocessing import LabelEncoder
dframe['Gender']=LabelEncoder().fit_transform(dframe['Gender'])
dframe #only the gendar column is normalised

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510       1  19.0          19000.0          0
1    15810944       1  35.0          20000.0          0
2    15668575       0  26.0          43000.0          0
3    15603246       0  27.0          57000.0          0
4    15804002       1  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0          41000.0          1
396  15706071       1  51.0          23000.0          1
397  15654296       0  50.0          20000.0          1
398  15755018       1  36.0          33000.0          0
399  15594041       0  49.0          36000.0          1

[400 rows x 5 columns]

In [6]:
from sklearn.preprocessing import Normalizer #importing the normalizer
scaler=Normalizer() #initializing the normaliser
scaled_data=scaler.fit_transform(dframe) #fit and transforming the data---helps to find the maen and std dev and scale the data
scaled_data=pd.DataFrame(scaled_data,columns=dframe.columns) #convert normalized data to a new data frame which is scaled_data
scaled_data.head()

User ID        Gender       Age  EstimatedSalary  Purchased
0  0.999999  6.400196e-08  0.000001         0.001216        0.0
1  0.999999  6.324728e-08  0.000002         0.001265        0.0
2  0.999996  0.000000e+00  0.000002         0.002744        0.0
3  0.999993  0.000000e+00  0.000002         0.003653        0.0
4  0.999988  6.327438e-08  0.000001         0.004809        0.0

**MinMax Scaling**:-Tranforms features into range of 0 to 1.
Xnormalized = X – Xmin / Xmax – Xmin (here X is the value to be normalized)

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
print(scaler.fit_transform(dframe))

[[0.23263608 1.         0.02380952 0.02962963 0.        ]
 [0.98273164 1.         0.4047619  0.03703704 0.        ]
 [0.40992649 0.         0.19047619 0.20740741 0.        ]
 ...
 [0.35247659 0.         0.76190476 0.03703704 1.        ]
 [0.75771987 1.         0.42857143 0.13333333 0.        ]
 [0.1100476  0.         0.73809524 0.15555556 1.        ]]


**Z Score Normalization**:-

If a value is exactly equal to the mean of all the values of the feature, it will be normalized to 0. If it is below the mean, it will be a negative number, and if it is above the mean it will be a positive number. The size of those negative and positive numbers is determined by the standard deviation of the original feature. If the unnormalized data had a large standard deviation, the normalized values will be closer to 0.

In [8]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
print(scaler.fit_transform(dframe))

[[-0.93657932  1.02020406 -1.78179743 -1.49004624 -0.74593581]
 [ 1.66838653  1.02020406 -0.25358736 -1.46068138 -0.74593581]
 [-0.32087714 -0.98019606 -1.11320552 -0.78528968 -0.74593581]
 ...
 [-0.52039175 -0.98019606  1.17910958 -1.46068138  1.34059793]
 [ 0.88695546  1.02020406 -0.15807423 -1.07893824 -0.74593581]
 [-1.36231017 -0.98019606  1.08359645 -0.99084367  1.34059793]]


 **Log Scaling:-**
 Log scaling computes the log of the values to compress a wide range to a narrow range. In other words, it helps convert a skewed distribution to a normal distribution/less-skewed distribution. To perform the scaling, take the log values in a column and use them as the column instead.
 x'=log(x)
 eg:-24:log(24)=1.38


In [10]:
from sklearn.preprocessing import FunctionTransformer
transformer=FunctionTransformer()
print(transformer.fit_transform(dframe))

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510       1  19.0          19000.0          0
1    15810944       1  35.0          20000.0          0
2    15668575       0  26.0          43000.0          0
3    15603246       0  27.0          57000.0          0
4    15804002       1  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863       0  46.0          41000.0          1
396  15706071       1  51.0          23000.0          1
397  15654296       0  50.0          20000.0          1
398  15755018       1  36.0          33000.0          0
399  15594041       0  49.0          36000.0          1

[400 rows x 5 columns]


**Robust Scaling:-**
This Scaler removes the median and scales the data according to the quantile range (defaults to IQR: Interquartile Range). The IQR is the range between the 1st quartile (25th quantile) and the 3rd quartile (75th quantile).

In [11]:
from sklearn.preprocessing import RobustScaler
scaler=RobustScaler()
print(scaler.fit_transform(dframe))

[[-0.5649832   1.         -1.10769231 -1.13333333  0.        ]
 [ 0.94339165  1.         -0.12307692 -1.11111111  0.        ]
 [-0.20846809  0.         -0.67692308 -0.6         0.        ]
 ...
 [-0.32399468  0.          0.8        -1.11111111  1.        ]
 [ 0.49091317  1.         -0.06153846 -0.82222222  0.        ]
 [-0.81149764  0.          0.73846154 -0.75555556  1.        ]]
